web/router.ex
defmodule Superjobs.Router do
  use Superjobs.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug Superjobs.Plug.Locale, "pt-br"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Superjobs do
    pipe_through :browser # Use the default browser stack

    # The dummy route is never hit, but exists so that the router has a "/" path.
    get "/", PageController, :dummy
  end

  scope "/:locale", Superjobs do
    pipe_through [:browser]

    get "/", PageController, :index

    get "/bicos", PortfolioController, :bicos
    get "/estagiariosonline", PortfolioController, :estagiariosonline
    get "/pagueamigo", PortfolioController, :pagueamigo
    get "/dr-sintomas", PortfolioController, :dr_sintomas
  end

  # Other scopes may use custom stacks.
  # scope "/api", Superjobs do
  #   pipe_through :api
  # end
end

lib/superjobs/endpoint.ex
defmodule Superjobs.Endpoint do
  use Phoenix.Endpoint, otp_app: :superjobs

  socket "/socket", Superjobs.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :superjobs, gzip: false,
    only: ~w(css fonts videos images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  # plug Plug.RequestId
  # plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_superjobs_key",
    signing_salt: "g9LBi+zf"

  plug Superjobs.Router
end

lib/superjobs/plug/locale.ex
defmodule Superjobs.Plug.Locale do
  import Plug.Conn

  def init(default), do: default

  def call(conn, default) do
    locale = conn.params["locale"]
    is_ietf_tag = BCP47.valid?(locale, ietf_only: true)

    if is_ietf_tag && locale in Superjobs.Gettext.supported_locales do
      # Check if path contains a valid Locale
      conn |> assign_locale! locale
    else
      # Get locale based on user agent and redirect
      locale = List.first(extract_locale(conn)) || default
      # Invalid or missing locales redirect with user agent locale
      path = if is_ietf_tag do
        localized_path(conn.request_path, locale, conn.params["locale"])
      else
        localized_path(conn.request_path, 'pt-br')
      end
      conn |> redirect_to(path)
    end
  end

  defp assign_locale!(conn, value) do
    # Apply the locale as a process var and continue
    Gettext.put_locale(Superjobs.Gettext, value)
    conn
    |> assign(:locale, value)
  end

  defp extract_locale(conn) do
    if Blank.present? conn.params["locale"] do
      [conn.params["locale"] | extract_accept_language(conn)]
    else
      extract_accept_language(conn)
    end
    # Filter for only known locales
    |> Enum.filter(fn locale -> Enum.member?(Superjobs.Gettext.supported_locales, locale) end)
  end

  defp extract_accept_language(conn) do
    case conn |> get_req_header("accept-language") do
      [value|_] ->
        value
        |> String.split(",")
        |> Enum.map(&parse_language_option/1)
        |> Enum.sort(&(&1.quality > &2.quality))
        |> Enum.map(&(&1.tag))
      _ ->
        []
    end
  end

  defp parse_language_option(string) do
    captures = ~r/^(?<tag>[\w\-]+)(?:;q=(?<quality>[\d\.]+))?$/i
    |> Regex.named_captures(string)

    quality = case Float.parse(captures["quality"] || "1.0") do
      {val, _} -> val
      _ -> 1.0
    end

    %{tag: captures["tag"], quality: quality}
  end

  defp localized_path(request_path, locale, original) do
    # If locale is an ietf tag, we don't support it. In this case,
    # replace the tag with the new locale.
    ~r/(\/)#{original}(\/(?:.+)?|\?(?:.+)?|$)/
    |> Regex.replace(request_path, "\\1#{locale}\\2")
  end

  defp localized_path(request_path, locale) do
    # If locale is not an ietf tag, it is a page request.
    "/#{locale}#{request_path}"
  end

  defp redirect_to(conn, path) do
    # Apply query if present
    unless Blank.blank? conn.query_string do
      path = path <> "?#{conn.query_string}"
    end
    # Redirect
    conn |> Phoenix.Controller.redirect(to: path)
  end

end

lib/superjobs/repo.ex
defmodule Superjobs.Repo do
  use Ecto.Repo, otp_app: :superjobs
end

web/controllers/page_controller.ex
defmodule Superjobs.PageController do
  use Superjobs.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/portfolio_controller.ex
defmodule Superjobs.PortfolioController do
  use Superjobs.Web, :controller

  def bicos(conn, _params) do
    render conn, "bicos.html"
  end

  def estagiariosonline(conn, _params) do
    render conn, "estagiariosonline.html"
  end

  def pagueamigo(conn, _params) do
    render conn, "pagueamigo.html"
  end

  def dr_sintomas(conn, _params) do
    render conn, "dr_sintomas.html"
  end
end

web/views/error_view.ex
defmodule Superjobs.ErrorView do
  use Superjobs.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Superjobs.LayoutView do
  use Superjobs.Web, :view

  import Phoenix.Naming

  @doc """
  Renders current locale.
  """
  def locale do
    Gettext.get_locale(Superjobs.Gettext)
  end

  @doc """
  Provides tuples for all alternative languages supported.
  """
  def fb_locales do
    Superjobs.Gettext.supported_locales
    |> Enum.map(fn l ->
      # Cannot call `locale/0` inside guard clause
      current = locale
      case l do
        l when l == current -> {"og:locale", l}
        l -> {"og:locale:alternate", l}
      end
    end)
  end

  @doc """
  Provides tuples for all alternative languages supported.
  """
  def language_annotations(conn) do
    Superjobs.Gettext.supported_locales
    |> Enum.reject(fn l -> l == locale end)
    |> Enum.concat(["x-default"])
    |> Enum.map(fn l ->
      case l do
        "x-default" -> {"x-default", localized_url(conn, "")}
        l -> {l, localized_url(conn, "/#{l}")}
      end
    end)
  end

  defp localized_url(conn, alt) do
    # Replace current locale with alternative
    path = ~r/\/#{locale}(\/(?:[^?]+)?|$)/
    |> Regex.replace(conn.request_path, "#{alt}\\1")

    Phoenix.Router.Helpers.url(Superjobs.Router, conn) <> path
  end
end

web/views/page_view.ex
defmodule Superjobs.PageView do
  use Superjobs.Web, :view
end

web/views/portfolio_view.ex
defmodule Superjobs.PortfolioView do
  use Superjobs.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="<%= locale %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Superjobs Venture Capital - Startups">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Generate og:locale tags -->
    <%= for {property, content} <- fb_locales do %>
      <%= Phoenix.HTML.Tag.tag(:meta, property: property, content: content) %>
    <% end %>

    <!-- Generate link alternate tags -->
    <%= for {lang, path} <- language_annotations(@conn) do %>
      <%= Phoenix.HTML.Tag.tag(:link, rel: "alternate", hreflang: lang, href: path) %>
    <% end %>

    <title>Superjobs Venture Capital</title>
    <link rel="icon" href="/images/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,700|Lato:300,700" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-81388316-1', 'auto');
  ga('send', 'pageview');

    </script>

    <!-- <link href="//vjs.zencdn.net/5.19/video-js.min.css" rel="stylesheet"> -->
  </head>

  <body>
    <header id="header">
        <div class="navigation">
            <a href="#nav" class="cd-nav-trigger">
            Menu<span></span>
         </a>
            <!-- .cd-nav-trigger -->
        </div>

        <ul class="social-header">
          <li>
            <a href="<%= page_path(@conn, :index, "pt-br") %>">
              <img src="<%= static_path(@conn, "/images/flags/bra.png") %>" />
            </a>
          </li>
          <li>
            <a href="<%= page_path(@conn, :index, "en") %>">
              <img src="<%= static_path(@conn, "/images/flags/usa.png") %>" />
            </a>
          </li>
        </ul>
        <div class="logo">
          <a href="<%= page_path(@conn, :index, @locale) %>"><img src="/images/logo_v2.png" alt="Superjobs logo" width="212" /></a>
        </div>
        <nav class="cd-nav-container" id="nav">
            <div class="close-container">
                <a href="#0" class="cd-close-nav">Close</a>
            </div>

            <ul class="cd-nav">
                <li><a href="/#who-we-are"><%= gettext "Quem somos" %></a></li>
                <li><a href="/#our-vision"><%= gettext "Nossa visão" %></a></li>
                <li><a href="/#portfolio"><%= gettext "Portfólio" %></a></li>
                <li><a href="/#team"><%= gettext "Nosso Time" %></a></li>
                <li><a href="/#get-in-touch"><%= gettext "Contato" %></a></li>
            </ul>
            <!-- .cd-nav -->
        </nav>
    </header>

    <!--- TODO: Remove or fix
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    -->

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer>
      <%= gettext "SuperJobs Venture Capital - Todos os direitos reservados" %>
    </footer>

  
    <script>
      var tag = document.createElement('script');
      tag.src = "https://www.youtube.com/player_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    </script>    

    <!-- <script src="//vjs.zencdn.net/5.19/video.min.js"></script> -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

    <%# Typeform link popup form snippet %>
    <script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>


  </body>
</html>

web/templates/page/_get_in_touch.html.eex
<section class="container get-in-touch" id="get-in-touch">
	<div class="center title-section wow  fadeInDown">
		<h2 class="get-in-touch__header"><%= raw gettext "VAMOS <u>JUNTOS</u> ESCALAR O SEU EVEREST?" %></h2>
		<h2 class="get-in-touch__content"><%= gettext "FALE COM A GENTE" %></h2>

		<div class="get-in-touch__buttons">
			<a href="https://superjobs.typeform.com/to/e12rdZ" class="typeform-share link button" data-mode="1" target="_blank"><strong><%= gettext "Investidores" %></strong></a>
			<a href="https://superjobs.typeform.com/to/FWSdcy" class="typeform-share link button" data-mode="1" target="_blank"><strong><%= gettext "Startups" %></strong></a>
			<a href="#" class="link button" data-toggle="modal" data-target="#modal-press"><strong><%= gettext "Imprensa" %></strong></a>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="modal-press" tabindex="-1" role="dialog" aria-labelledby="modal-press">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title"><%= gettext "Assessoria de Imprensa" %></h4>
				</div>
				<div class="modal-body">
					<address>
						<p>
							<strong>E-mail: </strong> <a href="mailto:release@pressworks.com.br" title="release@pressworks.com.br" target="_blank">release@pressworks.com.br</a>
						</p>
						<p>
							<strong>Site: </strong> <a href="http://www.pressworks.com.br" title="www.pressworks.com.br" target="_blank">www.pressworks.com.br</a>
						</p>
						<p><strong>Telefone: </strong> (11) 4301-0161 / (11) 96025-5541</p>
					</address>
				</div>
			</div>
		</div>
	</div>
</section>

web/templates/page/_header.html.eex
<section class="sj-header">

    <h1 class="sj-header__title">
        SuperJobs Ventures
    </h1>

    <h2 class="sj-header__subtitle">
        <%= gettext "Investimentos de Alto Impacto"  %>
    </h2>

    <div class="sj-header__buttons">
        <a class="typeform-share link btn sj-header__button" href="https://bicos.typeform.com/to/e12rdZ" data-mode="1" target="_blank">
            <i class="fa fa-long-arrow-right"></i>
            <%= gettext "Investidores"  %>
        </a>
        <a class="typeform-share link btn sj-header__button" href="https://bicos.typeform.com/to/FWSdcy" data-mode="1" target="_blank">
            <i class="fa fa-long-arrow-right"></i>
            <%= gettext "Startups"  %>
        </a>
    </div>
</section>

web/templates/page/_our_vision.html.eex
<section class="our-vision" id="our-vision">
  <h2 class="container our-vision__header"><%= gettext "NOSSA VISÃO" %></h2>

  <div class="container our-vision__subheader">
    <div class="col-xs-12 col-md-2 our-vision__subheader__title"><%= raw gettext "Qual é o<br/> seu everest?" %></div>
    <div class="col-xs-12 col-md-10 our-vision__subheader__content">
      <%= gettext "O seu everest nada mais é que o seu propósito. Aquilo que traz sentido para tudo o que fazemos. Vidas não tem sentido sem propósito. Negócios não tem sentido sem propósito." %>
    </div>
  </div>

  <div class="our-vision__first-part">
    <div class="container">
      <div class="col-md-2">
      </div>
      <div class="col-md-10">
        <p>
          <%= raw gettext "O QUE TE <span class='our-vision__highlight'>MOVE?</span> O QUE TE FAZ ACORDAR CEDO COM UMA <span class='our-vision__highlight'>INQUIETAÇÃO INCONTROLÁVEL?</span> O QUE <span class='our-vision__highlight'>DILATA A SUA PUPILA, ACELERA O SEU CORAÇÃO?</span>" %>
        </p>

        <div class="our-vision__text-separator"></div>

        <p>
          <%= gettext "Passamos muitas vezes a vida toda sem entender porque estamos aqui, qual é a nossa missão." %>
        </p>
      </div>
    </div>
  </div>

  <div class="our-vision__second-part">
    <div class="container">
      <div class="col-md-2">
      </div>
      <div class="col-md-10">
        <p>
          <%= gettext "Baseado nesse entendimento que a SuperJobs definiu o seu propósito:" %>
        </p>
        <p class="our-vision__highlight">
          <%= gettext "Ajudar pessoas e negócios a prosperar no novo mundo, na nova economia, de forma orgânica, engajada, transparente, preocupada não somente em gerar mais valores tangíveis, mas também os intangíveis." %>
        </p>
        <p>
          <%= gettext "Nada mais orgânico nos negócios do que entender o comportamento humano, as necessidades das pessoas. O mundo em que vivemos nunca presenciou tamanha transformação em tão pouco tempo. E o que todos nós não estávamos acostumados se tornou uma realidade: a mudança é agora o estado natural das coisas." %>
        </p>
        <p>
          <%= gettext "E só temos uma alternativa, ou andamos na frente dessas transformações, sendo precursores, investindo em inovação, criando tendências….ou seremos mais um no meio da enorme multidão." %>
        </p>
      </div>
    </div>
  </div>
</section>

web/templates/page/_portfolio.html.eex
<section id="portfolio" class="portifolio block-area">
    <div class="container">
        <div class="center title-section wow fadeInDown">
            <h5>NOSSO</h5>
            <h3 class="lrg">PORTOFÓLIO</h3>
            <div class="separator">
                <span><i></i></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portfolio-filter">
                    <a href="#" class="filter transition active" data-filter="*">Tudo</a>
                    <a href="#" class="filter transition" data-filter=".marketplaces-tag">Marketplaces</a>
                    <a href="#" class="filter transition" data-filter=".fintech-tag">Fintech</a>
                    <a href="#" class="filter transition" data-filter=".ai-tag">AI</a>
                    <a href="#" class="filter transition" data-filter=".health-tag">Health</a>
                </div>
            </div>
        </div>

        <div class="grid masonry">

            <div class="masonry-item web-design marketplaces-tag wow fadeInUp" data-wow-delay=".1s">
                <div class="work-img">
                    <figure class="portfolio-effect">
                        <img src="/images/portfolio/bicos.png" alt="img">
                        <figcaption>
                            <h3>Bicos</h3>
                            <a href="<%= portfolio_path(@conn, :bicos, @locale) %>"><i class="fa fa-search"></i></a>
                        </figcaption>
                    </figure>
                </div>
            </div>

            <div class="masonry-item web-design marketplaces-tag wow fadeInUp" data-wow-delay=".2s">
                <div class="work-img">
                    <figure class="portfolio-effect">
                        <img src="/images/portfolio/estagiarios.png" alt="img">
                        <figcaption>
                            <h3>Estagiários Online</h3>
                            <a href="<%= portfolio_path(@conn, :estagiariosonline, @locale) %>"><i class="fa fa-search"></i></a>
                        </figcaption>
                    </figure>
                </div>
            </div>

            <div class="masonry-item web-design fintech-tag wow fadeInUp" data-wow-delay=".3s">
                <div class="work-img">
                    <figure class="portfolio-effect">
                        <img src="/images/portfolio/pagueamigo.png" alt="img">
                        <figcaption>
                            <h3>Pague Amigo</h3>
                            <a href="<%= portfolio_path(@conn, :pagueamigo, @locale) %>"><i class="fa fa-search"></i></a>
                        </figcaption>
                    </figure>
                </div>
            </div>

            <div class="masonry-item web-design ai-tag health-tag wow fadeInUp" data-wow-delay=".4s">
                <div class="work-img">
                    <figure class="portfolio-effect">
                        <img src="/images/portfolio/drsintomas.png" alt="img">
                        <figcaption>
                            <h3>Dr. Sintomas</h3>
                            <a href="<%= portfolio_path(@conn, :dr_sintomas, @locale) %>"><i class="fa fa-search"></i></a>
                        </figcaption>
                    </figure>
                </div>
            </div>

        </div>
    </div>
</section>

web/templates/page/_process_slider.html.eex
<section class="process-slider">
  <div class="process-slider__nav">
    <h3><%= gettext "NOSSO PROCESSO" %></h3>
    <div class="process-slider__nav__jumps">
      <a href="#ideias-validacoes" class="tab-01 active"><%= gettext "1. IDÉIAS & VALIDAÇÕES" %></a>
      <a href="#funding" class="tab-02"><%= gettext "2. FUNDING" %></a>
      <a href="#desenvolvimento" class="tab-03"><%= gettext "3. DESENVOLVIMENTO" %></a>
      <a href="#growth" class="tab-04"><%= gettext "4. GROWTH" %></a>
    </div>
  </div>

  <div id="process-slider">
    <div id="ideias-validacoes" class="process-slider__slide" style="background: #004562">
      <div class="process-slider__slide__content">
        <img class="process-slider__slide" src="<%= static_path(@conn, "/images/process-slider/1_pt-br.jpg") %>" />
        <img class="process-slider__slide" src="<%= static_path(@conn, "/images/process-slider/1_en.jpg") %>" />
      </div>
    </div>
    <div id="funding" class="process-slider__slide" style="background: #836334">
      <div class="process-slider__slide__content">
        <img class="process-slider__slide" src="<%= static_path(@conn, "/images/process-slider/2_pt-br.jpg") %>" />
        <img class="process-slider__slide" src="<%= static_path(@conn, "/images/process-slider/2_en.jpg") %>" />
      </div>
    </div>
    <div id="desenvolvimento" class="process-slider__slide" style="background: #242841">
      <div class="process-slider__slide__content">
        <img class="process-slider__slide" src="<%= static_path(@conn, "/images/process-slider/3_pt-br.jpg") %>" />
        <img class="process-slider__slide" src="<%= static_path(@conn, "/images/process-slider/3_en.jpg") %>" />
      </div>
    </div>
    <div id="growth" class="process-slider__slide" style="background: #2F241C">
      <div class="process-slider__slide__content">
        <img class="process-slider__slide" src="<%= static_path(@conn, "/images/process-slider/4_pt-br.jpg") %>" />
        <img class="process-slider__slide" src="<%= static_path(@conn, "/images/process-slider/4_en.jpg") %>" />
      </div>
    </div>
  </div>
</section>

web/templates/page/_team.html.eex
<section id="team" class="team">
	<div class="container">
		<div class="center title-section wow fadeInDown">
			<h2 class="title"><%= gettext "Nosso Time" %></h2>
		</div>
		<!-- title-section -->

		<div class="team-content">
			<div id="section-marcos" class="team-member wow fadeInUp">
				<figure class="member-image">
					<img src="<%= static_path(@conn, "/images/team/round-marcos.png") %>" alt="img">
				</figure>
				<div class="team-details center">
					<h4>Marcos Botelho</h4>
					<h5>Founder</h5>
					<p>
						<%= gettext("Fundador e CEO da SuperJobs, Marcos Botelho é um apaixonado por tecnologia, com 20 anos de experiência no mercado de comunicação, foi fundador da agência Midia (2001) e da Elemídia Mall (2008), onde tinha como sócio o publicitário Roberto Justus, após a venda das duas empresas para o grupo Abril (2010) e passar alguns anos na Abril como Diretor Comercial, Botelho voltou a empreender em 2014, idealizando e fundando a SuperJobs Ventures.") %>
					</p>
				</div>
			</div>

			<!-- team-member -->
			<div id="section-andre" class="team-member wow fadeInUp">
				<figure class="member-image">
					<img src="<%= static_path(@conn, "/images/team/round-andre.png") %>" alt="img">
				</figure>
				<div class="team-details center">
					<h4>Andre Martins</h4>
					<h5>Co-Founder</h5>
					<p>
						<%= gettext("Andre Martins é presidente da VB desde abril de 2000. Formado em Administração de Empresas pela Fundação Álvares Penteado (FAAP), com cursos de especialização no INSEAD, na França, e pela Fundação Dom Cabral, em Minas Gerais, André Martins foi presidente do Lide Jovem, grupo de jovens executivos e empresários, até dezembro de 2013 e é membro do Conselho Empresarial do Instituto Ayrton Senna. Além disso, André desenvolve um papel de investidor em startups desde 2008, investindo em empresas como Pto de Contato, Fintech ContaUm, PetiteBox e co-fundou a SuperJobs Ventures.") %>
					</p>
				</div>
			</div>	
			<!-- team-member -->

			<div id="section-catharina" class="team-member wow fadeInUp">
				<figure class="member-image">
					<img src="<%= static_path(@conn, "/images/team/round-catharina.png") %>" alt="img">
				</figure>
				<div class="team-details center">
					<h4>Catharina Gaissler</h4>
					<h5>Portfolio Manager</h5>
					<p>
						<%= gettext("Com 6 Anos de Experiência no mercado brasileiro de Marketing e Comunicação, Catharina atuou 4 anos como Diretora de Marketing e Gerenciamento de Operações na Construtora brasileira Gaissler & Solon LTDA. Posteriormente, na ideia de trazer uma ideia escalável para a América Latina, tornou-se sócia e Diretora Geral no Brasil da startup de hospitalidade nova-iorquina Host Lifestyle Group, desenvolvendo estratégias de captação, realizando parceria com grandes grupos no país.") %>
					</p>
				</div>
			</div>	
			<!-- team-member -->

			<div id="section-eriane" class="team-member wow fadeInUp">
				<figure class="member-image">
					<img src="<%= static_path(@conn, "/images/team/round-eriane.png") %>" alt="img">
				</figure>
				<div class="team-details center">
					<h4>Eriane Vila Nova</h4>
					<h5>Product and Planner</h5>
					<p>
						<%= gettext("Formada em Produção Publicitária pela Universidade Anhembi Morumbi, Eriane atuou no setor de Administração Financeira do Banco Indusval & Partners no Brasil. Seguindo para o setor de Comunicação, acumulou 3 anos de experiência no setor de Gerenciamento de Projetos e Quality Assurance na Agência de Publicidade Urban Summer.") %>
					</p>
				</div>
			</div>
			<!-- team-member -->

		</div>

		<!-- row -->
	</div>
	<!-- container -->
</section>

web/templates/page/_testimonial_cases.html.eex
<section class="testimonial-client container-fluid">

    <div class="col-md-6 no-padding" >
        <div class="client">
        </div>
    </div>

    <div class="testimonial col-md-6 no-padding">
        <h3>CASES</h3>
        <div class="owl-clients">

            <div class="item">
                <p>Com a SuperJobs foi possível escalar a nossa equipe de desenvolvimento.</p>
                <img src="<%= static_path(@conn, "/images/testimonial/testimonial1.jpg") %>" alt="" />
                <div class="testimonial-details">
                    <h5>Leonardo Oshiro</h5>
                    <h6>CTO</h6>
                </div>
            </div>

            <div class="item">
                <p>O grupo ajudou a reunir todos os pontos fortes de cada uma de nossas iniciativas sobre um mesmo teto.</p>
                <img src="<%= static_path(@conn, "/images/testimonial/testimonial2.jpg") %>" alt="" />
                <div class="testimonial-details">
                    <h5>Marcos Botelho</h5>
                    <h6>CEO</h6>
                </div>
            </div>

            <div class="item">
                <p>Auxiliou na captação estratégica de fundos para expandirmos a nossa operação para todas as cidades do Brasil.</p>
                <img src="<%= static_path(@conn, "/images/testimonial/testimonial3.jpg") %>" alt="" />
                <div class="testimonial-details">
                    <h5>Kleber Costa</h5>
                    <h6>CEO</h6>
                </div>
            </div>

        </div>
    </div>
</section>

web/templates/page/index.html.eex
<%= render "_header.html", assigns %>
<%= render "_who_we_are.html", assigns %>
<%= render "_our_vision.html", assigns %>
<%= render "_process_slider.html", assigns %>
<%= render "_cases.html", assigns %>
<%= render "_team.html", assigns %>
<%= render "_get_in_touch.html", assigns %>